### ISSUE TITLE
No Internet detected on Windows 7

### ISSUE THREAD

**Issue by hunsbct** [streambinder/spotitube#41] opened 2019-05-13 17:56 UTC
Running on Windows 7, self-built.

When I call the program with `spotitube <Spotify playlist URI> -disable-gui -disable-browser-opening`, it starts with a warning about a missing Genius token. I'm not too concerned with that functionality unless it's the root of the problem here.
Then it goes on to say that no tracks were indexed, and when I visit the tinyurl link it responds with an error message that says "INVALID_CLIENT: Invalid redirect URI". 0 tracks are indexed and 0 are linked. Any ideas what I might be doing wrong?

![Screenshot_36](https://user-images.githubusercontent.com/15640258/57642988-a1ac4580-7586-11e9-8e71-35165adf8efd.png)

**Comment by streambinder** [comment] 2019-05-14 09:07
Hi. Unfortunately, I have never checked how `spotitube` is working upon Windows.
I can only assure you the problem is not `No track index has been found.` related, probably `Are you sure you're connected to the internet?`, instead.
@Coul33t , can you give @hunsbct any tip?

**Comment by Coul33t** [comment] 2019-05-14 10:36
Hello,
The missing Genius token isn't important indeed. Are you being a proxy?

**Comment by streambinder** [comment] 2019-05-29 12:51
Closing due to missing feedback.

**Closed by streambinder** 2019-05-29 12:51 UTC
Labels: Need more informations
